baseURL = 'https://build4me2.github.io/'
locale = 'en-US'
title = 'Manisha Chand'
theme = 'PaperMod'

# --- Permalinks ---
[permalinks]
  posts = "/:slug/"

# --- Menu ---
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 10

# --- Services / SEO ---
[services]
  [services.googleAnalytics]
    id = ""

# --- Params ---
[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true

  # Social links in header

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/build4me2"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/manesha63"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/manisha-chand-393908304/"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:chandmanisha00@gmail.com"

# --- Taxonomies ---
[taxonomies]
  tag = "tags"
  category = "categories"
