#!/usr/bin/env python3
"""Build the Hugo site with clean, deterministic settings.

The generated bytes are compared without normalization. Reproducibility checks
ignore only host filesystem metadata (timestamps, ownership, and permissions),
which is not part of a deployed Pages artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PINNED_HUGO_VERSION = "0.162.0"
BUILD_CLOCK = "2026-01-01T00:00:00Z"
SOURCE_DATE_EPOCH = "1767225600"
HUGO_VERSION_PATTERN = re.compile(r"\bhugo v(?P<version>\d+\.\d+\.\d+)(?:[-+][^\s]+)?")


class BuildError(RuntimeError):
    """A deterministic build precondition or invocation failed."""


def build_environment() -> dict[str, str]:
    environment = os.environ.copy()
    environment.update({
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "TZ": "UTC",
        "SOURCE_DATE_EPOCH": SOURCE_DATE_EPOCH,
    })
    return environment


def verify_hugo() -> None:
    try:
        result = subprocess.run(
            ["hugo", "env", "--logLevel", "debug"],
            cwd=ROOT,
            env=build_environment(),
            text=True,
            capture_output=True,
            timeout=15,
        )
    except FileNotFoundError as exc:
        raise BuildError(f"Hugo Extended {PINNED_HUGO_VERSION} is required, but 'hugo' was not found") from exc
    except subprocess.TimeoutExpired as exc:
        raise BuildError("Hugo toolchain check timed out after 15 seconds") from exc

    output = result.stdout or result.stderr
    first_line = output.splitlines()[0].strip() if output.splitlines() else ""
    match = HUGO_VERSION_PATTERN.search(first_line)
    extended = "+extended" in first_line or "github.com/bep/golibsass=" in output
    if result.returncode or match is None:
        raise BuildError(
            "Hugo toolchain mismatch: could not identify the installed version; "
            f"expected Hugo Extended {PINNED_HUGO_VERSION}"
        )
    actual_version = match.group("version")
    if actual_version != PINNED_HUGO_VERSION or not extended:
        actual_name = f"Hugo{' Extended' if extended else ''} {actual_version}"
        raise BuildError(
            f"Hugo toolchain mismatch: found {actual_name}; expected Hugo Extended {PINNED_HUGO_VERSION}"
        )


def clean_directory(path: Path, label: str) -> None:
    """Remove an output/cache path without ever following a directory symlink."""
    absolute = Path(os.path.abspath(path))
    if absolute == ROOT or absolute == Path(absolute.anchor):
        raise BuildError(f"refusing to clean {label} path {absolute}")
    if absolute.is_symlink() or absolute.is_file():
        absolute.unlink()
    elif absolute.exists():
        shutil.rmtree(absolute)


def stable_diagnostic(output: str, destination: Path, cache: Path) -> str:
    value = output.replace(str(destination), "<destination>").replace(str(cache), "<cache>").replace(str(ROOT), "<repository>")
    lines = []
    for raw_line in value.splitlines():
        line = raw_line.strip()
        if not line or re.match(r"^(Start building sites|Total in) ", line):
            continue
        line = re.sub(r"\b\d+(?:\.\d+)?\s*(?:ms|milliseconds|seconds?)\b", "<duration>", line)
        if line not in lines:
            lines.append(line)
    return "\n".join(lines) or "Hugo returned a non-zero status without a diagnostic"


def build(destination: Path, cache: Path | None = None, *, preflight: bool = True) -> None:
    destination = Path(os.path.abspath(destination))
    if preflight:
        verify_hugo()
    if cache is None:
        with tempfile.TemporaryDirectory(prefix="hugo-build-cache-") as temporary:
            _build(destination, Path(temporary))
    else:
        _build(destination, Path(os.path.abspath(cache)))


def _build(destination: Path, cache: Path) -> None:
    # Removing the entire destination is stronger than Hugo's stale-file cleanup
    # and guarantees that deleted/renamed generated files cannot survive.
    clean_directory(destination, "destination")
    clean_directory(cache, "cache")
    cache.mkdir(parents=True, exist_ok=False)
    destination.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "hugo",
        "--cleanDestinationDir",
        "--noBuildLock",
        "--ignoreCache",
        "--minify",
        "--environment", "production",
        "--clock", BUILD_CLOCK,
        "--cacheDir", str(cache),
        "--destination", str(destination),
    ]
    try:
        result = subprocess.run(
            command,
            cwd=ROOT,
            env=build_environment(),
            text=True,
            capture_output=True,
            timeout=120,
        )
    except FileNotFoundError as exc:
        raise BuildError("Hugo disappeared after the toolchain preflight") from exc
    except subprocess.TimeoutExpired as exc:
        raise BuildError("Hugo build timed out after 120 seconds") from exc
    if result.returncode:
        raise BuildError("Hugo build failed:\n" + stable_diagnostic(result.stderr or result.stdout, destination, cache))


def tree_manifest(root: Path) -> list[tuple[str, str]]:
    """Return a path-sorted byte manifest; intentionally exclude only FS metadata."""
    manifest: list[tuple[str, str]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink() or not path.is_file():
            if path.is_symlink():
                raise BuildError(f"generated output contains unsupported symlink: {relative}")
            continue
        manifest.append((relative, hashlib.sha256(path.read_bytes()).hexdigest()))
    return manifest


def verify_reproducible() -> None:
    verify_hugo()
    with tempfile.TemporaryDirectory(prefix="hugo-reproducible-") as temporary:
        root = Path(temporary)
        first = root / "first"
        second = root / "second"
        build(first, root / "cache-first", preflight=False)
        build(second, root / "cache-second", preflight=False)
        first_manifest = tree_manifest(first)
        second_manifest = tree_manifest(second)
        if first_manifest != second_manifest:
            first_map = dict(first_manifest)
            second_map = dict(second_manifest)
            paths = sorted(set(first_map) | set(second_map))
            findings = []
            for path in paths:
                if first_map.get(path) != second_map.get(path):
                    state = "content differs"
                    if path not in first_map:
                        state = "missing from first build"
                    elif path not in second_map:
                        state = "missing from second build"
                    findings.append(f"- {path}: {state}")
            raise BuildError("clean builds are not reproducible:\n" + "\n".join(findings))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--destination", type=Path, default=ROOT / "public")
    parser.add_argument("--verify-reproducible", action="store_true", help="compare two isolated clean builds")
    args = parser.parse_args()
    try:
        if args.verify_reproducible:
            verify_reproducible()
            print("Reproducible build verified: generated paths and bytes are identical")
        else:
            build(args.destination)
            try:
                shown = Path(os.path.abspath(args.destination)).relative_to(ROOT).as_posix()
            except ValueError:
                shown = str(Path(os.path.abspath(args.destination)))
            print(f"Clean deterministic site built at {shown}")
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
